# Generated by Django 3.2.18 on 2023-04-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('개발', '개발'), ('CS', 'CS'), ('신기술', '신기술')], max_length=3),
        ),
    ]
